### ISSUE TITLE
Sourcemap : false create a sourcemap

### ISSUE THREAD

**Issue by Sliverside** [willrowe/sublime-sass-compile#1]
hi,
I fixed that by editing pyton file line 244-245 from that :
 `		if  settings["sourcemap"]:
			rules.append("--sourcemap")`
to that :
`		if not settings["sourcemap"]:
			rules.append("--sourcemap=none")`
sorry for my english...

**Comment by willrowe** [comment]
Are you saying that it is generating a sourcemap when the setting is `False`?

**Comment by Sliverside** [comment]
Yes

**Comment by willrowe** [comment]
Ok, thanks for reporting this
Could you provide version numbers if possible?
Version numbers for the following would be great:
- OS (where Sublime Text is installed)
- Sublime Text
- sass (command line tool)

**Comment by Sliverside** [comment]
- Windows 10 : version 1703, system version 15063.296
- Sublime text 3 : build 3126 
- sass : 3.4.23

**Comment by willrowe** [comment]
Thanks so much, I'll take a look when I have a chance.

**Comment by Sliverside** [comment]
Ok thank you !

**Comment by willrowe** [comment]
Thank you so much for reporting this and including the code sample, it fixed the issue.
v0.2.1 has just been tagged with the fix.

**Comment by Sliverside** [comment]
I am happy to have helped you !
