### ISSUE TITLE
Editing partial did not recompile scss/sass files that import them.

### ISSUE THREAD

**Issue by Sliverside** [willrowe/sublime-sass-compile#2]
Hi, thanks you in advance !

**Comment by willrowe** [comment]
Is this related to #1 or a separate issue?

**Comment by Sliverside** [comment]
It's a separate issue.

**Comment by willrowe** [comment]
What `sasscompile` settings are you using in the project settings file and how are the Sass files organized?

**Comment by Sliverside** [comment]
I use scss, and all scss files are in the same folder.
this is my `sasscompile` 
`"sasscompile" settings :
		{
			"cache": false,
			"cache-location": null,
			"compile-on-save": true,
			"css-location": "",
			"debug-info": false,
			"line-numbers": false,
			"sourcemap": false,
			"style": "compact",
			"syntax": "scss"
		}`

**Comment by willrowe** [comment]
Thanks for sending that, I'll see if I can reproduce the issue and let you know if I need any more information.

**Comment by Sliverside** [comment]
Ok, thank you !

**Comment by willrowe** [comment]
I tested this out, but was not able to reproduce the issue as described.
Can you please send the directory structure of your Sass files so I can see the names being used?
Please also include which file is the partial and which is the one importing it.

**Comment by Sliverside** [comment]
[Catacombes.zip](https://github.com/willrowe/sublime-sass-compile/files/1088241/Catacombes.zip)
site/
-- css/
 - '_animations.scss'
 - '_history.scss'
 - '_main_header.scss'
 - '_responsive.scss'
 - '_vars.scss'
 - 'style.css'
 - 'style.css.map'
 - 'style.scss'

**Comment by willrowe** [comment]
I believe the issue here is that this plugin does not officially support Windows. There is some code in determining where partials are included which will only work on *nix.

While there are no plans to explicitly add support for Windows at this time, this particular issue may be cleared up in a v1.x release. Thanks again for reporting this.
